<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <OutputPath>bin\Desktop\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>obj\Desktop\$(Configuration)\</IntermediateOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <MonoGamePlatform Condition="'$(MonoGamePlatform)' == ''">DesktopGL</MonoGamePlatform>
    <DefineConstants>$(DefineConstants);MONOGAME;MG_$(MonoGamePlatform)</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MonoGame.Framework\MonoGame.Framework.Native.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(MonoGamePlatform)' == 'DesktopVK'">
    <Content Include="..\Artifacts\native\mgruntime\desktopvk\macosx\Debug\libmgruntime.dylib" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup Condition="'$(MonoGamePlatform)' == 'DesktopGL'">
    <Content Include="..\Artifacts\native\mgruntime\desktopgl\macosx\Debug\libmgruntime.dylib" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>